У цьому домашньому завданні ми будемо працювати з набором даних Tips. Нижче інформація про нього.

Про датасет:

Tips - це датасет, який містить інформацію про рахунки та чайові в ресторані.

Колонки датасету:

- total_bill - загальна сума рахунку (долари)
- tip - розмір чайових (долари)
- sex - стать відвідувача (Male/Female)
- smoker - чи курить (Yes/No)
- day - день тижня (Thur/Fri/Sat/Sun)
- time - час відвідування (Lunch/Dinner)
- size - розмір групи (кількість людей)
Джерело: Оригінальні дані зібрані в одному з американських ресторанів у 1990-х роках. Скачати і переглянути набір даних можна тут: https://www.kaggle.com/datasets/sakshisatre/tips-dataset

А також ми вже вивантажили файл з даними і завантажили вам у Матеріали до цього модуля.

1. Завантаження та огляд

Завантажте датасет Tips (Чайові) з файла у матеріалах tips.csv.

Виведіть (кожен пункт оцінюється в 0.5 бала):

- Перші 5 рядків
- Розмір датасету (shape)
- Назви всіх колонок
- Інформацію про типи даних (info)

In [3]:
import pandas as pd

# Завантаження датасету Titanic з CSV
df = pd.read_csv('tip.csv')

In [6]:
display(df.head())

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [7]:
display(df.shape)

(244, 7)

In [8]:
display(df.columns)

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [9]:
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

None

2. Базова вибірка даних

Виберіть та виведіть (кожен пункт оцінюється в 0.5 бала):

- Колонку total_bill (загальний рахунок)
- Колонки total_bill та tip (чайові) разом
- Перші 10 рядків
- Рядок з індексом 5

In [32]:
# Колонку total_bill (загальний рахунок)
total_bill = df['total_bill']
display(total_bill)

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [33]:
# Колонки total_bill та tip (чайові) разом
selected = df[['total_bill', 'tip']]
print(type(selected)) 

print(selected)
#або
display(selected)

<class 'pandas.core.frame.DataFrame'>
     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [34]:
#Перші 10 рядків
print(df.iloc[0:10]) 
#або
display(df.iloc[0:10])

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [35]:
#Рядок з індексом 5
print(df.iloc[5])
#або
display(df.iloc[5:6])

total_bill     25.29
tip             4.71
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 5, dtype: object

   total_bill   tip   sex smoker  day    time  size
5       25.29  4.71  Male     No  Sun  Dinner     4

3. Фільтрація даних

Відфільтруйте повний набір даних та виведіть (кожен пункт оцінюється в 0.5 бала):

- Всі рахунки більше 20 доларів (total_bill > 20)
- Всі відвідувачі-жінки (sex == 'Female')
- Рахунки на вечерю (time == 'Dinner')
- Рахунки на вечерю з сумою чеку більше 30 доларів
- Для виведення результатів фільтрації:

- зберегти результат у окрему змінну
- показати кількість записів у відфільтрованому наборі
- вивести перші 5 записів відфільтрованого набору.

In [42]:
#Всі рахунки більше 20 доларів (total_bill > 20)
filtered = df[df['total_bill'] > 20]
display(filtered)

     total_bill   tip     sex smoker  day    time  size
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
5         25.29  4.71    Male     No  Sun  Dinner     4
7         26.88  3.12    Male     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
237       32.83  1.17    Male    Yes  Sat  Dinner     2
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2

[97 rows x 7 columns]

In [43]:
filtered = df[df['total_bill'] > 20]
print(len(filtered))
display(filtered.head())

97

   total_bill   tip     sex smoker  day    time  size
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
7       26.88  3.12    Male     No  Sun  Dinner     4

In [45]:
#Всі відвідувачі-жінки (sex == 'Female')
filtered = df[df['sex'] == 'Female']
print(len(filtered))
display(filtered.head())

87

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
11       35.26  5.00  Female     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2
16       10.33  1.67  Female     No  Sun  Dinner     3

In [46]:
#Рахунки на вечерю (time == 'Dinner')
filtered = df[df['time'] == 'Dinner']
print(len(filtered))
display(filtered.head())

176

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [47]:
#Рахунки на вечерю з сумою чеку більше 30 доларів
filtered = df[(df['time'] == 'Dinner') & (df['total_bill'] > 30)]
print(len(filtered))
display(filtered.head())

27

    total_bill   tip     sex smoker  day    time  size
11       35.26  5.00  Female     No  Sun  Dinner     4
23       39.42  7.58    Male     No  Sat  Dinner     4
39       31.27  5.00    Male     No  Sat  Dinner     3
44       30.40  5.60    Male     No  Sun  Dinner     4
47       32.40  6.00    Male     No  Sun  Dinner     4

4. Описова статистика

Обчисліть (кожен пункт оцінюється в 0.5 бала):

- Середній розмір рахунку на всьому наборі даних
- Максимальні чайові
- Кількість пропущених значень у всіх колонках
- Скільки в наборі даних рахунків за обіди і за вечері

In [53]:
# Середній розмір рахунку на всьому наборі даних
df['total_bill'].mean()

np.float64(19.78594262295082)

In [54]:
# Максимальні чайові
df['tip'].max()

10.0

In [55]:
# Кількість пропущених значень у всіх колонках
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [56]:
# Скільки в наборі даних рахунків за обіди і за вечері
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

5. Статистика із групуванням

Обчисліть (кожен пункт оцінюється в 0.5 бала):

- Середній рахунок за статтю (groupby sex)
- Середні чайові за днем тижня (groupby day)
- Скільки відвідувачів у кожен день

In [59]:
# Групування за однією колонкою
#Середній рахунок за статтю (groupby sex)

by_sex = df.groupby('sex')['total_bill'].mean()
print("Середній рахунок за статтю:")
by_sex

Середній рахунок за статтю:

sex
Female    18.056897
Male      20.744076
Name: total_bill, dtype: float64

In [60]:
by_sex = df.groupby('sex')['total_bill'].mean().reset_index()
display(by_sex)

      sex  total_bill
0  Female   18.056897
1    Male   20.744076

In [62]:
#Середні чайові за днем тижня (groupby day)

by_day = df.groupby('day')['tip'].mean().reset_index().round(2)
display(by_day)

    day   tip
0   Fri  2.73
1   Sat  2.99
2   Sun  3.26
3  Thur  2.77

In [68]:
#Скільки відвідувачів у кожен день
by_day = df.groupby('day')['day'].count().reset_index(name='count')
display(by_day)

    day  count
0   Fri     19
1   Sat     87
2   Sun     76
3  Thur     62

6. Створення нової колонки

Створіть нову колонку tip_percentage - відсоток чайових від загальної суми рахунку. Виведіть перші 10 рядків з новою колонкою.

In [77]:
df['tip_percentage'] = ((df['tip'] / df['total_bill']) * 100).round(2)
display(df['tip_percentage'].head(10))
#or
display(df[['total_bill', 'tip', 'tip_percentage']].head(10))

0     5.94
1    16.05
2    16.66
3    13.98
4    14.68
5    18.62
6    22.81
7    11.61
8    13.03
9    21.85
Name: tip_percentage, dtype: float64

   total_bill   tip  tip_percentage
0       16.99  1.01            5.94
1       10.34  1.66           16.05
2       21.01  3.50           16.66
3       23.68  3.31           13.98
4       24.59  3.61           14.68
5       25.29  4.71           18.62
6        8.77  2.00           22.81
7       26.88  3.12           11.61
8       15.04  1.96           13.03
9       14.78  3.23           21.85

7. Сортування

Відсортуйте датасет і виведіть результат сортування в кожному випадку окремо (кожен пункт оцінюється в 0.5 бала):

- За розміром рахунку (зростання)
- За чайовими (спадання)
- Додатково виведіть топ-5 найбільших чайових використовуючи метод nlargest.

In [78]:
#За розміром рахунку (зростання)

df_sorted = df.sort_values('total_bill')
df_sorted_desc = df.sort_values('total_bill', ascending=False)

In [79]:
df_sorted.head()

     total_bill   tip     sex smoker   day    time  size  tip_percentage
67         3.07  1.00  Female    Yes   Sat  Dinner     1           32.57
92         5.75  1.00  Female    Yes   Fri  Dinner     2           17.39
111        7.25  1.00  Female     No   Sat  Dinner     1           13.79
172        7.25  5.15    Male    Yes   Sun  Dinner     2           71.03
149        7.51  2.00    Male     No  Thur   Lunch     2           26.63

In [84]:
#За чайовими (спадання)
df_sorted_desc = df.sort_values('tip', ascending=False)
display(df_sorted_desc.head())

     total_bill    tip   sex smoker   day    time  size  tip_percentage
170       50.81  10.00  Male    Yes   Sat  Dinner     3           19.68
212       48.33   9.00  Male     No   Sat  Dinner     4           18.62
23        39.42   7.58  Male     No   Sat  Dinner     4           19.23
59        48.27   6.73  Male     No   Sat  Dinner     4           13.94
141       34.30   6.70  Male     No  Thur   Lunch     6           19.53

In [89]:
#Додатково виведіть топ-5 найбільших чайових використовуючи метод nlargest.
top5 = df['tip'].nlargest(5)
display(df.nlargest(5, 'tip'))

     total_bill    tip   sex smoker   day    time  size  tip_percentage
170       50.81  10.00  Male    Yes   Sat  Dinner     3           19.68
212       48.33   9.00  Male     No   Sat  Dinner     4           18.62
23        39.42   7.58  Male     No   Sat  Dinner     4           19.23
59        48.27   6.73  Male     No   Sat  Dinner     4           13.94
141       34.30   6.70  Male     No  Thur   Lunch     6           19.53